-- Auto-generated from settlement_list.txt
-- Run in Supabase SQL editor

-- 1. Regions (counties)
INSERT INTO locations (name_al, name_en, slug, type) VALUES
  ('Berat', 'Berat', 'berat', 'region'),
  ('Bulqizë', 'Bulqizë', 'bulqize', 'region'),
  ('Delvinë', 'Delvinë', 'delvine', 'region'),
  ('Devoll', 'Devoll', 'devoll', 'region'),
  ('Dibër', 'Dibër', 'diber', 'region'),
  ('Durrës', 'Durrës', 'durres', 'region'),
  ('Elbasan', 'Elbasan', 'elbasan', 'region'),
  ('Fier', 'Fier', 'fier', 'region'),
  ('Gjirokastër', 'Gjirokastër', 'gjirokaster', 'region'),
  ('Gramsh', 'Gramsh', 'gramsh', 'region'),
  ('Has', 'Has', 'has', 'region'),
  ('Kavajë', 'Kavajë', 'kavaje', 'region'),
  ('Kolonjë', 'Kolonjë', 'kolonje', 'region'),
  ('Korçë', 'Korçë', 'korce', 'region'),
  ('Krujë', 'Krujë', 'kruje', 'region'),
  ('Kuçovë', 'Kuçovë', 'kucove', 'region'),
  ('Kukës', 'Kukës', 'kukes', 'region'),
  ('Kurbin', 'Kurbin', 'kurbin', 'region'),
  ('Lezhë', 'Lezhë', 'lezhe', 'region'),
  ('Librazhd', 'Librazhd', 'librazhd', 'region'),
  ('Lushnjë', 'Lushnjë', 'lushnje', 'region'),
  ('Malësi e Madhe', 'Malësi e Madhe', 'malesi-e-madhe', 'region'),
  ('Mallakastër', 'Mallakastër', 'mallakaster', 'region'),
  ('Mat', 'Mat', 'mat', 'region'),
  ('Mirditë', 'Mirditë', 'mirdite', 'region'),
  ('Peqin', 'Peqin', 'peqin', 'region'),
  ('Përmet', 'Përmet', 'permet', 'region'),
  ('Pogradec', 'Pogradec', 'pogradec', 'region'),
  ('Pukë', 'Pukë', 'puke', 'region'),
  ('Sarandë', 'Sarandë', 'sarande', 'region'),
  ('Shkodër', 'Shkodër', 'shkoder', 'region'),
  ('Skrapar', 'Skrapar', 'skrapar', 'region'),
  ('Tepelenë', 'Tepelenë', 'tepelene', 'region'),
  ('Tiranë', 'Tiranë', 'tirane', 'region'),
  ('Tropojë', 'Tropojë', 'tropoje', 'region'),
  ('Vlorë', 'Vlorë', 'vlore', 'region')
ON CONFLICT (slug) DO NOTHING;

-- 2. Cities
INSERT INTO locations (name_al, name_en, slug, type) VALUES
  ('Tiranë', 'Tiranë', 'tirane', 'city'),
  ('Durrës', 'Durrës', 'durres', 'city'),
  ('Vlorë', 'Vlorë', 'vlore', 'city'),
  ('Sarandë', 'Sarandë', 'sarande', 'city'),
  ('Kavajë', 'Kavajë', 'kavaje', 'city'),
  ('Shkodër', 'Shkodër', 'shkoder', 'city'),
  ('Fier', 'Fier', 'fier', 'city'),
  ('Lezhë', 'Lezhë', 'lezhe', 'city'),
  ('Korçë', 'Korçë', 'korce', 'city'),
  ('Shëngjin', 'Shëngjin', 'shengjin', 'city'),
  ('Elbasan', 'Elbasan', 'elbasan', 'city'),
  ('Kamëz', 'Kamëz', 'kamez', 'city'),
  ('Lushnje', 'Lushnje', 'lushnje', 'city'),
  ('Himarë', 'Himarë', 'himare', 'city'),
  ('Vorë', 'Vorë', 'vore', 'city'),
  ('Pogradec', 'Pogradec', 'pogradec', 'city'),
  ('Shijak', 'Shijak', 'shijak', 'city'),
  ('Orikum', 'Orikum', 'orikum', 'city'),
  ('Berat', 'Berat', 'berat', 'city'),
  ('Divjakë', 'Divjakë', 'divjake', 'city'),
  ('Krujë', 'Krujë', 'kruje', 'city'),
  ('Manëz', 'Manëz', 'manez', 'city'),
  ('Gjirokastër', 'Gjirokastër', 'gjirokaster', 'city'),
  ('Sukth', 'Sukth', 'sukth', 'city'),
  ('Rrogozhinë', 'Rrogozhinë', 'rrogozhine', 'city'),
  ('Peshkopi', 'Peshkopi', 'peshkopi', 'city'),
  ('Gramsh', 'Gramsh', 'gramsh', 'city'),
  ('Përmet', 'Përmet', 'permet', 'city'),
  ('Mamurras', 'Mamurras', 'mamurras', 'city'),
  ('Kuçovë', 'Kuçovë', 'kucove', 'city'),
  ('Bajram curri', 'Bajram curri', 'bajram-curri', 'city'),
  ('Koplik', 'Koplik', 'koplik', 'city'),
  ('Tepelenë', 'Tepelenë', 'tepelene', 'city'),
  ('Kukës', 'Kukës', 'kukes', 'city'),
  ('Burrel', 'Burrel', 'burrel', 'city'),
  ('Fushë Krujë', 'Fushë Krujë', 'fushe-kruje', 'city'),
  ('Kërrabë', 'Kërrabë', 'kerrabe', 'city'),
  ('Bilisht', 'Bilisht', 'bilisht', 'city'),
  ('Bulqizë', 'Bulqizë', 'bulqize', 'city'),
  ('Konispol', 'Konispol', 'konispol', 'city'),
  ('Milot', 'Milot', 'milot', 'city'),
  ('Patos', 'Patos', 'patos', 'city'),
  ('Selenicë', 'Selenicë', 'selenice', 'city'),
  ('Ura Vajgurore', 'Ura Vajgurore', 'ura-vajgurore', 'city'),
  ('Vau i dejës', 'Vau i dejës', 'vau-i-dejes', 'city')
ON CONFLICT (slug) DO NOTHING;

-- 3. Villages (format: "Village - ParentCity")
INSERT INTO locations (name_al, name_en, slug, type) VALUES
  ('Golem - Kavajë', 'Golem - Kavajë', 'golem-kavaje', 'village'),
  ('Paskuqan - Tiranë', 'Paskuqan - Tiranë', 'paskuqan-tirane', 'village'),
  ('Palasë - Vlorë', 'Palasë - Vlorë', 'palase-vlore', 'village'),
  ('Hamallaj - Durrës', 'Hamallaj - Durrës', 'hamallaj-durres', 'village'),
  ('Laknas - Tiranë', 'Laknas - Tiranë', 'laknas-tirane', 'village'),
  ('Sauk - Tiranë', 'Sauk - Tiranë', 'sauk-tirane', 'village'),
  ('Qerret - Durrës', 'Qerret - Durrës', 'qerret-durres', 'village'),
  ('Kashar - Tiranë', 'Kashar - Tiranë', 'kashar-tirane', 'village'),
  ('Farkë - Tiranë', 'Farkë - Tiranë', 'farke-tirane', 'village'),
  ('Golem - Lushnjë', 'Golem - Lushnjë', 'golem-lushnje', 'village'),
  ('Lalëz - Durrës', 'Lalëz - Durrës', 'lalez-durres', 'village'),
  ('Yzberish - Tiranë', 'Yzberish - Tiranë', 'yzberish-tirane', 'village'),
  ('Borsh - Vlorë', 'Borsh - Vlorë', 'borsh-vlore', 'village'),
  ('Lundër - Tiranë', 'Lundër - Tiranë', 'lunder-tirane', 'village'),
  ('Mjull Bathore - Tiranë', 'Mjull Bathore - Tiranë', 'mjull-bathore-tirane', 'village'),
  ('Fushë - Fier', 'Fushë - Fier', 'fushe-fier', 'village'),
  ('Qeret - Kavajë', 'Qeret - Kavajë', 'qeret-kavaje', 'village'),
  ('Selitë - Elbasan', 'Selitë - Elbasan', 'selite-elbasan', 'village'),
  ('Jalë - Vlorë', 'Jalë - Vlorë', 'jale-vlore', 'village'),
  ('Spille - Kavajë', 'Spille - Kavajë', 'spille-kavaje', 'village'),
  ('Arapaj - Durrës', 'Arapaj - Durrës', 'arapaj-durres', 'village'),
  ('Selitë - Tiranë', 'Selitë - Tiranë', 'selite-tirane', 'village'),
  ('Bathore - Tiranë', 'Bathore - Tiranë', 'bathore-tirane', 'village'),
  ('Shkallnur - Durrës', 'Shkallnur - Durrës', 'shkallnur-durres', 'village'),
  ('Velipojë - Shkodër', 'Velipojë - Shkodër', 'velipoje-shkoder', 'village'),
  ('Bërzhitë - Tiranë', 'Bërzhitë - Tiranë', 'berzhite-tirane', 'village'),
  ('Ksamil - Sarandë', 'Ksamil - Sarandë', 'ksamil-sarande', 'village'),
  ('Mullet - Tiranë', 'Mullet - Tiranë', 'mullet-tirane', 'village'),
  ('Vaqarr - Tiranë', 'Vaqarr - Tiranë', 'vaqarr-tirane', 'village'),
  ('Xhafzotaj - Durrës', 'Xhafzotaj - Durrës', 'xhafzotaj-durres', 'village'),
  ('Mëzez - Tiranë', 'Mëzez - Tiranë', 'mezez-tirane', 'village'),
  ('Tragjas - Vlorë', 'Tragjas - Vlorë', 'tragjas-vlore', 'village'),
  ('Adriatik - Durrës', 'Adriatik - Durrës', 'adriatik-durres', 'village'),
  ('Akërni - Vlorë', 'Akërni - Vlorë', 'akerni-vlore', 'village'),
  ('Petrelë - Tiranë', 'Petrelë - Tiranë', 'petrele-tirane', 'village'),
  ('Shetaj - Durrës', 'Shetaj - Durrës', 'shetaj-durres', 'village'),
  ('Borsh - Devoll', 'Borsh - Devoll', 'borsh-devoll', 'village'),
  ('Dajt - Tiranë', 'Dajt - Tiranë', 'dajt-tirane', 'village'),
  ('Ishull  Lezhë - Lezhë', 'Ishull  Lezhë - Lezhë', 'ishull-lezhe-lezhe', 'village'),
  ('Babrru Qëndër, Kodër e Kuqe - Tiranë', 'Babrru Qëndër, Kodër e Kuqe - Tiranë', 'babrru-qender-koder-e-kuqe-tirane', 'village'),
  ('Kënetë - Durrës', 'Kënetë - Durrës', 'kenete-durres', 'village'),
  ('Laç - Mat', 'Laç - Mat', 'lac-mat', 'village'),
  ('Linzë - Tiranë', 'Linzë - Tiranë', 'linze-tirane', 'village'),
  ('Prush - Tiranë', 'Prush - Tiranë', 'prush-tirane', 'village'),
  ('Qeparo Fushë - Vlorë', 'Qeparo Fushë - Vlorë', 'qeparo-fushe-vlore', 'village'),
  ('Rinas - Krujë', 'Rinas - Krujë', 'rinas-kruje', 'village'),
  ('Rrashbull - Durrës', 'Rrashbull - Durrës', 'rrashbull-durres', 'village'),
  ('Shkozë - Elbasan', 'Shkozë - Elbasan', 'shkoze-elbasan', 'village'),
  ('Baldushk - Tiranë', 'Baldushk - Tiranë', 'baldushk-tirane', 'village'),
  ('Blerimaj - Kavajë', 'Blerimaj - Kavajë', 'blerimaj-kavaje', 'village'),
  ('Bllacë - Bulqizë', 'Bllacë - Bulqizë', 'bllace-bulqize', 'village'),
  ('Farkë e Madhe - Tiranë', 'Farkë e Madhe - Tiranë', 'farke-e-madhe-tirane', 'village'),
  ('Guri i Zi - Shkodër', 'Guri i Zi - Shkodër', 'guri-i-zi-shkoder', 'village'),
  ('Karpen - Kavajë', 'Karpen - Kavajë', 'karpen-kavaje', 'village'),
  ('Krutje e Poshtme - Lushnjë', 'Krutje e Poshtme - Lushnjë', 'krutje-e-poshtme-lushnje', 'village'),
  ('Kryemëdhej - Kavajë', 'Kryemëdhej - Kavajë', 'kryemedhej-kavaje', 'village'),
  ('Lin - Pogradec', 'Lin - Pogradec', 'lin-pogradec', 'village'),
  ('Lukovë - Vlorë', 'Lukovë - Vlorë', 'lukove-vlore', 'village'),
  ('Maminas - Durrës', 'Maminas - Durrës', 'maminas-durres', 'village'),
  ('Marikaj - Tiranë', 'Marikaj - Tiranë', 'marikaj-tirane', 'village'),
  ('Priskë e Madhe - Tiranë', 'Priskë e Madhe - Tiranë', 'priske-e-madhe-tirane', 'village'),
  ('Rinia - Durrës', 'Rinia - Durrës', 'rinia-durres', 'village'),
  ('Shënavlash - Durrës', 'Shënavlash - Durrës', 'shenavlash-durres', 'village'),
  ('Tale 1 - Lezhë', 'Tale 1 - Lezhë', 'tale-1-lezhe', 'village'),
  ('Bisht Kamëz - Durrës', 'Bisht Kamëz - Durrës', 'bisht-kamez-durres', 'village'),
  ('Daias - Tiranë', 'Daias - Tiranë', 'daias-tirane', 'village'),
  ('Fllakë - Durrës', 'Fllakë - Durrës', 'fllake-durres', 'village'),
  ('Ibë e Poshtme - Tiranë', 'Ibë e Poshtme - Tiranë', 'ibe-e-poshtme-tirane', 'village'),
  ('Ishëm - Durrës', 'Ishëm - Durrës', 'ishem-durres', 'village'),
  ('Ishull  Shëngjin - Lezhë', 'Ishull  Shëngjin - Lezhë', 'ishull-shengjin-lezhe', 'village'),
  ('Kaninë - Vlorë', 'Kaninë - Vlorë', 'kanine-vlore', 'village'),
  ('Karpen - Durrës', 'Karpen - Durrës', 'karpen-durres', 'village'),
  ('Katundi i Ri - Tiranë', 'Katundi i Ri - Tiranë', 'katundi-i-ri-tirane', 'village'),
  ('Kolonjë - Lushnjë', 'Kolonjë - Lushnjë', 'kolonje-lushnje', 'village'),
  ('Kotë - Vlorë', 'Kotë - Vlorë', 'kote-vlore', 'village'),
  ('Momël - Kavajë', 'Momël - Kavajë', 'momel-kavaje', 'village'),
  ('Novoselë - Vlorë', 'Novoselë - Vlorë', 'novosele-vlore', 'village'),
  ('Picall - Tiranë', 'Picall - Tiranë', 'picall-tirane', 'village'),
  ('Prezë - Tiranë', 'Prezë - Tiranë', 'preze-tirane', 'village'),
  ('Shëngjin - Tiranë', 'Shëngjin - Tiranë', 'shengjin-tirane', 'village'),
  ('Voskopojë - Korçë', 'Voskopojë - Korçë', 'voskopoje-korce', 'village'),
  ('Yrshek - Tiranë', 'Yrshek - Tiranë', 'yrshek-tirane', 'village'),
  ('Agonas - Kavajë', 'Agonas - Kavajë', 'agonas-kavaje', 'village'),
  ('Aliko - Delvinë', 'Aliko - Delvinë', 'aliko-delvine', 'village'),
  ('Allprenaj - Lushnjë', 'Allprenaj - Lushnjë', 'allprenaj-lushnje', 'village'),
  ('Arbanë - Tiranë', 'Arbanë - Tiranë', 'arbane-tirane', 'village'),
  ('Bizë - Durrës', 'Bizë - Durrës', 'bize-durres', 'village'),
  ('Boboshticë - Korçë', 'Boboshticë - Korçë', 'boboshtice-korce', 'village'),
  ('Bogë - Malësi e Madhe', 'Bogë - Malësi e Madhe', 'boge-malesi-e-madhe', 'village'),
  ('Borç, Hamallaj - Durrës', 'Borç, Hamallaj - Durrës', 'borc-hamallaj-durres', 'village'),
  ('Cerkovinë - Vlorë', 'Cerkovinë - Vlorë', 'cerkovine-vlore', 'village'),
  ('Çetë - Kavajë', 'Çetë - Kavajë', 'cete-kavaje', 'village'),
  ('Çukas i Vjetër - Lushnjë', 'Çukas i Vjetër - Lushnjë', 'cukas-i-vjeter-lushnje', 'village'),
  ('Dardhë - Korçë', 'Dardhë - Korçë', 'dardhe-korce', 'village'),
  ('Domën - Kavajë', 'Domën - Kavajë', 'domen-kavaje', 'village'),
  ('Domje - Tiranë', 'Domje - Tiranë', 'domje-tirane', 'village'),
  ('Draç - Durrës', 'Draç - Durrës', 'drac-durres', 'village'),
  ('Dukat - Vlorë', 'Dukat - Vlorë', 'dukat-vlore', 'village'),
  ('Ferraj - Tiranë', 'Ferraj - Tiranë', 'ferraj-tirane', 'village'),
  ('fshatrat - Tiranë', 'fshatrat - Tiranë', 'fshatrat-tirane', 'village'),
  ('Fushë Prezë - Tiranë', 'Fushë Prezë - Tiranë', 'fushe-preze-tirane', 'village'),
  ('Gjilekë - Vlorë', 'Gjilekë - Vlorë', 'gjileke-vlore', 'village'),
  ('Golem i Madh - Lushnjë', 'Golem i Madh - Lushnjë', 'golem-i-madh-lushnje', 'village'),
  ('Golemas - Kavajë', 'Golemas - Kavajë', 'golemas-kavaje', 'village'),
  ('Gosë - Kavajë', 'Gosë - Kavajë', 'gose-kavaje', 'village'),
  ('Guzaj - Durrës', 'Guzaj - Durrës', 'guzaj-durres', 'village'),
  ('Helmas - Kavajë', 'Helmas - Kavajë', 'helmas-kavaje', 'village'),
  ('Kakavie - Gjirokastër', 'Kakavie - Gjirokastër', 'kakavie-gjirokaster', 'village'),
  ('Kanaparaj - Kavajë', 'Kanaparaj - Kavajë', 'kanaparaj-kavaje', 'village'),
  ('Kasharaj - Lushnjë', 'Kasharaj - Lushnjë', 'kasharaj-lushnje', 'village'),
  ('Këmishtaj - Lushnjë', 'Këmishtaj - Lushnjë', 'kemishtaj-lushnje', 'village'),
  ('Klos - Mallakastër', 'Klos - Mallakastër', 'klos-mallakaster', 'village'),
  ('Kryeluzaj - Kavajë', 'Kryeluzaj - Kavajë', 'kryeluzaj-kavaje', 'village'),
  ('Kuç i Zi - Korçë', 'Kuç i Zi - Korçë', 'kuc-i-zi-korce', 'village'),
  ('Kullaj - Shkodër', 'Kullaj - Shkodër', 'kullaj-shkoder', 'village'),
  ('Laç (Sanxhak) - Kurbin', 'Laç (Sanxhak) - Kurbin', 'lac-sanxhak-kurbin', 'village'),
  ('Lanabreges - Tiranë', 'Lanabreges - Tiranë', 'lanabreges-tirane', 'village'),
  ('Lekaj - Kavajë', 'Lekaj - Kavajë', 'lekaj-kavaje', 'village'),
  ('Levan - Fier', 'Levan - Fier', 'levan-fier', 'village'),
  ('Manati - Lezhë', 'Manati - Lezhë', 'manati-lezhe', 'village'),
  ('Marqinet - Tiranë', 'Marqinet - Tiranë', 'marqinet-tirane', 'village'),
  ('Mazrek - Tiranë', 'Mazrek - Tiranë', 'mazrek-tirane', 'village'),
  ('Mborje - Korçë', 'Mborje - Korçë', 'mborje-korce', 'village'),
  ('Mifol - Vlorë', 'Mifol - Vlorë', 'mifol-vlore', 'village'),
  ('Mumajes - Tiranë', 'Mumajes - Tiranë', 'mumajes-tirane', 'village'),
  ('Panaja - Vlorë', 'Panaja - Vlorë', 'panaja-vlore', 'village'),
  ('Paskuqan Fushë - Tiranë', 'Paskuqan Fushë - Tiranë', 'paskuqan-fushe-tirane', 'village'),
  ('Perondi - Kuçovë', 'Perondi - Kuçovë', 'perondi-kucove', 'village'),
  ('Peshkëpi - Vlorë', 'Peshkëpi - Vlorë', 'peshkepi-vlore', 'village'),
  ('Pezë Helmës - Tiranë', 'Pezë Helmës - Tiranë', 'peze-helmes-tirane', 'village'),
  ('Piqeras - Vlorë', 'Piqeras - Vlorë', 'piqeras-vlore', 'village'),
  ('Pirg - Korçë', 'Pirg - Korçë', 'pirg-korce', 'village'),
  ('Plug - Lushnjë', 'Plug - Lushnjë', 'plug-lushnje', 'village'),
  ('Polizhan - Berat', 'Polizhan - Berat', 'polizhan-berat', 'village'),
  ('Poro - Vlorë', 'Poro - Vlorë', 'poro-vlore', 'village'),
  ('Priskë e Vogël - Tiranë', 'Priskë e Vogël - Tiranë', 'priske-e-vogel-tirane', 'village'),
  ('Qeparo fshat - Vlorë', 'Qeparo fshat - Vlorë', 'qeparo-fshat-vlore', 'village'),
  ('Ravonik - Korçë', 'Ravonik - Korçë', 'ravonik-korce', 'village'),
  ('Rilë - Lezhë', 'Rilë - Lezhë', 'rile-lezhe', 'village'),
  ('Rubjek,Xhafzotaj - Durrës', 'Rubjek,Xhafzotaj - Durrës', 'rubjekxhafzotaj-durres', 'village'),
  ('Sharrë - Tiranë', 'Sharrë - Tiranë', 'sharre-tirane', 'village'),
  ('Shëngjergj - Tiranë', 'Shëngjergj - Tiranë', 'shengjergj-tirane', 'village'),
  ('Sherishtë - Vlorë', 'Sherishtë - Vlorë', 'sherishte-vlore', 'village'),
  ('Shishtufinë - Tiranë', 'Shishtufinë - Tiranë', 'shishtufine-tirane', 'village'),
  ('Shkallë - Sarandë', 'Shkallë - Sarandë', 'shkalle-sarande', 'village'),
  ('Shytaj - Tiranë', 'Shytaj - Tiranë', 'shytaj-tirane', 'village'),
  ('Surrel - Tiranë', 'Surrel - Tiranë', 'surrel-tirane', 'village'),
  ('Trevllazër - Vlorë', 'Trevllazër - Vlorë', 'trevllazer-vlore', 'village'),
  ('Vadardhë - Durrës', 'Vadardhë - Durrës', 'vadardhe-durres', 'village'),
  ('Vishaj - Tiranë', 'Vishaj - Tiranë', 'vishaj-tirane', 'village'),
  ('Vllahinë - Vlorë', 'Vllahinë - Vlorë', 'vllahine-vlore', 'village'),
  ('Vranisht - Vlorë', 'Vranisht - Vlorë', 'vranisht-vlore', 'village'),
  ('Vuno - Vlorë', 'Vuno - Vlorë', 'vuno-vlore', 'village'),
  ('Xhyherinë - Vlorë', 'Xhyherinë - Vlorë', 'xhyherine-vlore', 'village'),
  ('Zvërnec - Vlorë', 'Zvërnec - Vlorë', 'zvernec-vlore', 'village')
ON CONFLICT (slug) DO NOTHING;
